
DELIMITER $$
CREATE PROCEDURE wk(IN i INT)
BEGIN
DECLARE na VARCHAR(3);
DECLARE inp VARCHAR(2);
SET inp=i;
IF(i<10)THEN
SET inp=CONCAT('0',i);
END IF;
SET na=CONCAT('z',inp);
INSERT INTO dccp_user_weight VALUES('z',na,1);
END $$

CREATE PROCEDURE wk2()
BEGIN
DECLARE i INT;
SET i=1;
WHILE i<3 DO 
call wk(i);
SET i=i+1;
END WHILE;
END $$

DELIMITER ;
CALL wk2();
DROP PROCEDURE IF EXISTS wk;
DROP PROCEDURE IF EXISTS wk2;